export { MovieCard, Movies } from './Movies'
export { Preloader } from './Preloader/Preloader'
export { SearchMovies } from './Search/SearchMovies'
export { SearchType } from './SearchType/SearchType'
export { SearchTypeInput } from './SearchTypeInput/SearchTypeInput'
